## The following requests can be tested using vscode with the "REST client" extension installed.

### GetProject
GET http://localhost:7071/api/GetProject
content-type: application/json

{   
    "ProjectId": "A01"
}

### CreateProject
POST http://localhost:7071/api/UpsertProject HTTP/1.1
content-type: application/json

{   
    "ProjectId": "A02",
    "Name":"TestProject"
}